# Generated by Django 5.2.17 on 2026-09-12 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration_version', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=16)),
                ('mode', models.CharField(max_length=24)),
                ('snapshot', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('next_action', models.JSONField(default=dict)),
                ('diagnostics', models.JSONField(default=list)),
                ('solve_seconds', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OperatorDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('confirm', 'Confirm'), ('override', 'Override')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='grid.optimizationrun')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='grid.optimizationrun')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('overrides', models.JSONField(default=dict)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='grid.optimizationrun')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scenario', to='grid.optimizationrun')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('state', models.CharField(default='Arunachal Pradesh', max_length=100)),
                ('district', models.CharField(default='Papum Pare', max_length=100)),
                ('latitude', models.FloatField(default=27.2297)),
                ('longitude', models.FloatField(default=93.3412)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=80)),
                ('archived', models.BooleanField(default=False)),
                ('configuration_version', models.PositiveIntegerField(default=1)),
                ('provenance', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.organization')),
            ],
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='grid.site'),
        ),
        migrations.CreateModel(
            name='LoadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('provenance', models.CharField(default='simulated_from_published_totals', max_length=80)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='load_profile', to='grid.site')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generator', to='grid.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchableLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexible_loads', to='grid.site')),
            ],
        ),
        migrations.CreateModel(
            name='BatteryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='grid.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SitePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='grid.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('provenance', models.CharField(default='operator', max_length=40)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='grid.site')),
            ],
            options={
                'ordering': ['-timestamp', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SolarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar', to='grid.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator')], max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grid_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('retrieved_at', models.DateTimeField()),
                ('source', models.CharField(max_length=40)),
                ('data', models.JSONField(default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='grid.site')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WindConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wind', to='grid.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('critical_kw', models.FloatField()),
                ('normal_kw', models.FloatField()),
                ('flexible_kw', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='grid.loadprofile')),
            ],
            options={
                'ordering': ['timestamp'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'timestamp'), name='unique_load_interval')],
            },
        ),
        migrations.CreateModel(
            name='SiteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grid.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'user'), name='unique_site_operator')],
            },
        ),
    ]
