# Generated by Django 5.2.17 on 2026-09-12 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuration_version', models.PositiveIntegerField()),
                ('provenance', models.CharField(max_length=40)),
                ('report', models.JSONField(default=dict)),
                ('artifacts', models.JSONField(default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_models', to='grid.site')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('configuration_version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('state', models.JSONField(default=dict)),
                ('options', models.JSONField(default=dict)),
                ('simulated_at', models.DateTimeField()),
                ('heartbeat', models.DateTimeField(null=True)),
                ('last_plan_at', models.DateTimeField(null=True)),
                ('events', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('latest_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.optimizationrun')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='grid.site')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='ControlCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='proposed', max_length=20)),
                ('proposal', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.optimizationrun')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='grid.livesession')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TelemetrySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('provenance', models.CharField(default='simulated', max_length=40)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='grid.livesession')),
            ],
            options={
                'ordering': ['-timestamp', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='livesession',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('site',), name='one_active_live_session'),
        ),
    ]
