# Generated by Django 5.2.17 on 2026-09-12 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_forecastmodel_livesession_controlcommand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='grid.optimizationrun')),
            ],
        ),
    ]
