import React,{useEffect,useRef,useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {MessageSquare,Send,Paperclip,Plus,ArrowUpRight,CheckCircle2,LoaderCircle,Square,History} from 'lucide-react';
import {api,downloadArtifact} from './api';
import {Dialog,ErrorNotice,number as n,timestamp} from './ui';
import ComparisonWindow from './ComparisonWindow';
import ChatReply from './ChatReply';
import useAssistantChat from './useAssistantChat';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
const done=['succeeded','failed','cancelled','unavailable'];
const statusLabels={queued:'Queued',running:'Working',waiting:'Waiting for verification',retrying:'Retry scheduled',clarification:'Needs your input',succeeded:'Verified completion',failed:'Stopped',cancelled:'Cancelled',unavailable:'Provider unavailable'};

function Facts({run}) {
 return <div className="chat-facts"><div><span>Critical service</span><b>{n(run.metrics?.critical_load_served_pct)}%</b></div><div><span>Diesel</span><b>{n(run.metrics?.diesel_litres)} L</b></div><div><span>Dispatch cost</span><b>₹{n(run.metrics?.dispatch_cost_inr)}</b></div><div><span>Minimum SOC</span><b>{n(run.metrics?.minimum_soc_pct)}%</b></div></div>;
}
function flatFields(value,prefix='') {
 return Object.fromEntries(Object.entries(value||{}).flatMap(([key,v])=>v&&typeof v==='object'&&!Array.isArray(v)?Object.entries(flatFields(v,prefix+key+'.')):[[prefix+key,Array.isArray(v)?JSON.stringify(v):v]]));
}
function Result({value}) {
 const [compare,setCompare]=useState(false),[error,setError]=useState('');const run=value.run;
 return <div className="chat-result"><ErrorNotice error={error}/>{run&&<><div className="section-heading"><b>{run.status==='infeasible'?'Analysis completed: no feasible plan':run.status==='failed'?'Analysis completed: solver failed':`Plan #${run.id} · ${run.status}`}</b><Link to={`/runs/${run.id}`}>Open plan <ArrowUpRight size={14}/></Link></div><small>{run.site_name} · {run.weather_source} · {timestamp(run.horizon_start)}</small>{run.intervals?.length>0&&<><Facts run={run}/><div className="chat-chart"><ResponsiveContainer><LineChart data={run.intervals}><CartesianGrid vertical={false}/><XAxis dataKey="timestamp" tickFormatter={v=>new Date(v).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:run.snapshot.site.timezone})} minTickGap={70}/><YAxis width={40}/><Tooltip formatter={v=>`${n(v)} kW`}/><Line dataKey="served_load" name="Supplied" type="stepAfter" stroke="#087f68" strokeWidth={2} dot={false}/><Line dataKey="diesel_power" name="Diesel" type="stepAfter" stroke="#d4805c" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></>}{run.diagnostics?.map((d,i)=><p key={i}>{d}</p>)}</>}
 {value.checks&&<div className="chat-checks">{value.checks.map(c=><Link key={c.name} to={`/runs/${c.run_id}`}><span>{c.name.replaceAll('_',' ')}</span><b>{['optimal','feasible'].includes(c.outcome)?`${n(c.metrics.critical_load_served_pct)}% served · ${n(c.metrics.diesel_litres)} L`:'No feasible plan'}</b></Link>)}</div>}
 {value.kind==='site'&&<><Link to={`/sites/${value.site.id}`}>{value.site.name} · site #{value.site.id}</Link><p>Configuration v{value.site.configuration_version}{value.template_used?' · explicitly accepted demo template':''}</p></>}
 {value.before&&value.after&&<div className="table-scroll"><table><thead><tr><th>Field</th><th>Before</th><th>After</th></tr></thead><tbody>{Object.entries(flatFields(value.after)).filter(([k,v])=>flatFields(value.before)[k]!==v).map(([k,v])=><tr key={k}><th>{k.replaceAll('_',' ')}</th><td>{String(flatFields(value.before)[k]??'—')}</td><td>{String(v)}</td></tr>)}</tbody></table></div>}
 {value.kind==='comparison'&&<><p>{value.runs.length} saved plans compared. {value.comparable?'Common horizon verified.':'Different bases; review the limitations.'}</p><button className="secondary" onClick={()=>setCompare(true)}>Open detailed comparison</button>{compare&&<ComparisonWindow runIds={value.runs.map(r=>r.id)} onClose={()=>setCompare(false)}/>}</>}
 {value.kind==='replay'&&<><Link to={`/sites/${value.site_id}`}>Replay #{value.session_id} · {value.state||'observed'}</Link>{value.telemetry&&<div className="chat-facts"><div><span>Supplied / requested</span><b>{n(value.telemetry.served_kw)} / {n(value.telemetry.demand_kw)} kW</b></div><div><span>Battery</span><b>{n(value.telemetry.soc_pct)}%</b></div></div>}</>}
 {value.kind==='command'&&<p>Command #{value.command_id}: {value.state||value.decision}</p>}{value.verification_scope&&<p className="chart-caption">{value.verification_scope}</p>}
 {value.kind==='review'&&<p>Plan #{value.run_id}: {value.decision}{value.reason&&` · ${value.reason}`}</p>}
 {value.kind==='import'&&<p>{value.intervals} hourly intervals · {n(value.daily_kwh)} kWh/day · source: CSV</p>}
 {value.kind==='model'&&<><b>Forecast model #{value.model_id}</b><div className="chat-facts">{['demand','solar'].map(k=><div key={k}><span>{k} test MAE</span><b>{n(value.report[k].ml_mae_kw,3)} kW</b><small>Baseline {n(value.report[k].baseline_mae_kw,3)} kW · {value.report[k].active?'Passed calibration gate':'Baseline retained'}</small></div>)}</div><p>{value.usage}</p></>}
 {value.kind==='answer'&&<><ChatReply text={value.text}/>{value.evidence?.some(f=>f.site||f.requested_plan)&&<details className="chat-answer-evidence"><summary>Sources used</summary>{value.evidence.map((f,i)=><div key={i}>{f.site&&<><Link to={`/sites/${f.site.id}`}>{f.site.name}</Link>{f.site.latest_run&&<><small>Plan #{f.site.latest_run.id} · {timestamp(f.site.latest_run.horizon_start)}</small><Facts run={f.site.latest_run}/></>}</>}{f.requested_plan&&<Facts run={f.requested_plan}/>}</div>)}</details>}</>}
 {value.artifact_id&&value.download&&<button className="primary" onClick={()=>downloadArtifact(value.artifact_id,`jeevangrid-report-${value.artifact_id}.${value.format==='csv'?'zip':value.format}`).catch(e=>setError(e.message))}>Download {value.format.toUpperCase()} · report #{value.artifact_id}</button>}
 </div>;
}
function WorkflowCard({job,refresh}) {
 const [error,setError]=useState('');
 if(job.status==='succeeded'&&job.result.kind==='answer')return <article className="chat-assistant" aria-label="JeevanGrid reply"><span className="chat-speaker">JeevanGrid</span><Result value={job.result}/></article>;
 return <article className={'workflow-card workflow-'+job.status}><div className="workflow-title">{job.status==='succeeded'?<CheckCircle2 size={19}/>:!done.includes(job.status)&&job.status!=='clarification'?<LoaderCircle size={18} className="spin"/>:<Square size={17}/>}<div><b>{job.label}</b><small>{statusLabels[job.status]} · #{job.id}</small></div>{!done.includes(job.status)&&<button className="text-button" onClick={()=>api(`/assistant/workflows/${job.id}/cancel`,{method:'POST'}).then(refresh).catch(e=>setError(e.message))}>Cancel</button>}</div>
 <div className="workflow-target">{job.sites?.map(s=>s.name).join(' · ')||job.inputs.site_data?.name||''}{job.inputs.mode&&<small>{{simulated:'Simulated weather',forecast:'Live weather forecast',historical:'NASA historical weather'}[job.inputs.mode]}{job.inputs.date&&` · ${job.inputs.date}`}</small>}{job.inputs.readings&&<small>{Object.entries(job.inputs.readings).map(([k,v])=>`${k.replaceAll('_',' ')}: ${v}`).join(' · ')}</small>}{job.inputs.overrides&&<small>{Object.entries(job.inputs.overrides).map(([k,v])=>`${k.replaceAll('_',' ')}: ${v}`).join(' · ')}</small>}</div>
 {job.status==='queued'&&Date.now()-Date.parse(job.created_at)>30000&&<p className="notice amber" role="status">This message is waiting to start. The assistant may be busy or its worker may be offline. You can keep waiting or cancel it.</p>}
 {job.status==='unavailable'&&<button className="secondary chat-retry" onClick={()=>api(`/assistant/workflows/${job.id}/retry`,{method:'POST'}).then(refresh).catch(e=>setError(e.message))}>Retry remaining steps</button>}<ErrorNotice error={error}/>{job.error&&<p className={job.status==='waiting'?'chart-caption':'notice amber'}>{job.error}</p>}{job.question&&job.status==='clarification'&&<p className="chat-question">{job.question}</p>}
 {job.status==='clarification'&&job.location_choices?.length>0&&<div className="chat-suggestions location-chat-options">{job.location_choices.map((place,i)=><button key={i} onClick={()=>api(`/assistant/workflows/${job.id}/clarify`,{method:'POST',body:{text:`Use this selected location: state ${place.state}, district ${place.district}, latitude ${place.latitude}, longitude ${place.longitude}, timezone ${place.timezone}.`}}).then(refresh).catch(e=>setError(e.message))}>{place.label}<small>{place.latitude}, {place.longitude}</small></button>)}</div>}
 {job.status==='succeeded'?<Result value={job.result}/>:done.includes(job.status)&&job.completed_changes>0&&<p>{job.completed_changes} completed steps remain saved. No further steps will run.</p>}
 {job.workflow!=='question'&&<details className="workflow-evidence"><summary>Task details</summary><div className="workflow-progress" aria-label="Workflow progress">{job.expected_steps.map(key=><span key={key} className={job.steps.some(s=>s.key===key)?'complete':''}>{job.steps.find(s=>s.key===key)?.label||key.replaceAll('_',' ')}</span>)}</div>{job.steps.map(s=><div key={s.key}><b>{s.label}</b><small>{timestamp(s.created_at)} · {s.verification.checks?.join(', ')}</small>{s.receipt.kind==='run'&&<Link to={`/runs/${s.receipt.id}`}>Saved plan #{s.receipt.id}</Link>}{s.receipt.kind==='site'&&<Link to={`/sites/${s.receipt.id}`}>Saved site #{s.receipt.id}</Link>}</div>)}<details><summary>Accepted inputs</summary><pre>{JSON.stringify(job.inputs,null,2)}</pre></details></details>}</article>;
}
function Chat({siteId=null,conversationId=null,onCreated=()=>{},user,restore=true,showHistoryLink=false}) {
 const {config,c,text,setText,error,busy,attachment,load,send,attach,fresh}=useAssistantChat({siteId,conversationId,onCreated,user,restore});
 const bottom=useRef(),file=useRef(),composer=useRef(),messages=useRef(),nearBottom=useRef(true);
 useEffect(()=>{if(!conversationId)composer.current?.focus()},[conversationId]);
 const progress=c?.workflows.map(job=>job.id+':'+job.status).join('|');
 useEffect(()=>{if(nearBottom.current)bottom.current?.scrollIntoView({block:'nearest'})},[c?.messages.length,progress]);
 function newChat(){fresh();nearBottom.current=true;composer.current?.focus()}
 const scope=c?.site_id||siteId;
 return <div className="assistant-chat"><div className="assistant-toolbar"><span title={scope?'This chat can access only this site.':'This chat uses the sites you can access.'}><i className="live-dot"/>{scope?`Site #${scope} only`:user.role==='admin'?'All sites':'Assigned sites'}</span><div className="chat-toolbar-actions">{showHistoryLink&&<Link className="chat-history-link" to="/assistant?history=1"><History size={15}/>History</Link>}<button type="button" className="secondary chat-new" aria-label="New chat" title="Start a fresh chat; previous chats stay in history" onClick={newChat}><Plus size={16}/>New chat</button></div></div>{config&&!config.configured&&<p className="notice amber">Add your Groq API key to enable chat.</p>}{config&&!config.enabled&&<p className="notice amber">The assistant is currently disabled.</p>}
 <div ref={messages} className={'assistant-messages'+(!c?.messages.length?' is-empty':'')} aria-label="Conversation" onScroll={()=>{const el=messages.current;nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<100}}><ErrorNotice error={error}/>{!c?.messages.length&&<div className="assistant-welcome"><span className="assistant-welcome-icon"><MessageSquare size={23}/></span><h2>How can I help?</h2></div>}
 {c?.messages.map(message=><React.Fragment key={message.id}><div className="chat-user"><span>You · {timestamp(message.created_at)}</span><p>{message.text}</p></div>{c.workflows.filter(j=>j.message_id===message.id).map(job=><WorkflowCard key={job.id} job={job} refresh={()=>load(c.id)}/>)}</React.Fragment>)}<div ref={bottom}/></div>
 <form className="assistant-composer" onSubmit={e=>{nearBottom.current=true;send(e)}}>{attachment&&<small>Attached #{attachment.id}: {attachment.name}</small>}<label className="sr-only" htmlFor="assistant-message">Message JeevanGrid assistant</label><textarea ref={composer} id="assistant-message" aria-describedby="assistant-keyboard-help" value={text} onChange={e=>setText(e.target.value)} rows={2} maxLength={16000} placeholder={c?.workflows.some(j=>j.status==='clarification')?'Add the missing information…':'Message JeevanGrid…'} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();nearBottom.current=true;send(e)}}}/><div><input ref={file} type="file" accept=".csv,text/csv" hidden onChange={attach}/><button type="button" className="icon-button" aria-label="Attach CSV" title="Attach CSV" disabled={busy||config?.enabled===false} onClick={()=>file.current.click()}><Paperclip size={18}/></button><small id="assistant-keyboard-help" className="sr-only">Enter to send. Shift + Enter for a new line.</small><button className="primary" disabled={busy||!text.trim()||config?.enabled===false}><Send size={16}/>{busy?'Sending…':'Send'}</button></div></form></div>;
}
export function AssistantWidget({user}) {
 const [open,setOpen]=useState(false),[runSite,setRunSite]=useState(null),location=useLocation(),match=location.pathname.match(/^\/sites\/(\d+)(?:\/|$)/),saved=location.pathname.match(/^\/runs\/(\d+)$/),querySite=location.pathname==='/data'?Number(new URLSearchParams(location.search).get('site')):null;
 const siteId=match?Number(match[1]):querySite||runSite?.id||null;
 useEffect(()=>{setOpen(false);setRunSite(null);if(saved){let active=true;api(`/optimization-runs/${saved[1]}`).then(r=>{if(active)setRunSite({id:r.site_id})}).catch(()=>{});return()=>{active=false}}},[location.pathname,location.search]);
 if(location.pathname==='/assistant')return null;
 return <><button className="assistant-launch" disabled={!!saved&&!runSite} onClick={()=>setOpen(true)} aria-label="Open JeevanGrid assistant"><MessageSquare size={19}/><span>Ask JeevanGrid</span></button>{open&&<Dialog title="JeevanGrid assistant" className="assistant-drawer" onClose={()=>setOpen(false)}><Chat key={siteId||'org'} user={user} siteId={siteId} showHistoryLink/></Dialog>}</>;
}
export default function AssistantPage({user}) {
 const [history,setHistory]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[key,setKey]=useState(0);
 const location=useLocation(),[historyOpen,setHistoryOpen]=useState(()=>new URLSearchParams(location.search).has('history'));
 useEffect(()=>{let active=true;api('/assistant/conversations').then(value=>{if(active)setHistory(value)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[selected,key]);
 return <div className="assistant-workspace"><header className="page-head assistant-page-head"><h1>Assistant</h1><button type="button" className="secondary chat-history-toggle" aria-expanded={historyOpen} aria-controls="assistant-history" onClick={()=>setHistoryOpen(value=>!value)}><History size={16}/>History</button></header><ErrorNotice error={error}/><div className={'assistant-page'+(historyOpen?' history-open':'')}><aside id="assistant-history" aria-label="Conversation history" hidden={!historyOpen}><h2>Recent chats</h2>{history.map(c=><button className={selected===c.id?'selected':''} key={c.id} onClick={()=>{setSelected(c.id);setHistoryOpen(false)}}><b>{c.title}</b><small>{timestamp(c.updated_at)}</small></button>)}{!history.length&&<p>No conversations yet.</p>}</aside><section className="panel"><Chat key={`${selected||'new'}-${key}`} conversationId={selected} restore={false} user={user} onCreated={id=>{setSelected(id);if(id===null)setKey(k=>k+1)}}/></section></div></div>;
}
