import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,BarChart,Bar} from 'recharts';
import {Dialog,ErrorNotice,number as n,timestamp} from './ui';
import {api} from './api';
import ExportMenu from './Reports';
const palette=['#087f68','#447fb3','#b87a32','#9463aa','#bd6353'];
export const measures=[['critical_load_served_pct','Critical service','%',1],['critical_unserved_kwh','Critical shortage','kWh',2],['normal_unserved_kwh','Normal shortage','kWh',2],['flexible_unserved_kwh','Unfinished flexible work','kWh',2],['served_kwh','Energy supplied','kWh',1],['dispatch_cost_inr','Dispatch cost','INR',2],['cost_per_kwh','Cost / supplied energy','INR/kWh',3],['diesel_litres','Diesel fuel','L',2],['diesel_l_per_kwh','Diesel / supplied energy','L/kWh',4],['renewable_share_pct','Renewable generation','%',1],['emissions_kg_co2','Combustion emissions','kg CO₂',2],['emissions_per_kwh','Emissions / supplied energy','kg CO₂/kWh',3],['minimum_soc_pct','Minimum battery','%',1],['reserve_margin_pp','Margin above reserve','pp',1]];
const hourly=[['diesel_power','Diesel','kW'],['served_load','Supplied demand','kW'],['critical_unserved','Critical shortage','kWh'],['battery_soc','Battery SOC','%'],['flexible_load_scheduled','Flexible work','kW']];
export function ComparisonDetails({data}) {
 const [metric,setMetric]=useState('cost_per_kwh'),[series,setSeries]=useState('diesel_power');
 const m=measures.find(r=>r[0]===metric),h=hourly.find(r=>r[0]===series);
 const points=data.runs[0]?.intervals.map((r,i)=>({time:r.timestamp,...Object.fromEntries(data.runs.map((run,j)=>['r'+j,run.intervals[i]?.[series]]))}))||[];
 const [view,setView]=useState('metrics');
 return <div className="comparison-workspace"><div className="comparison-identities">{data.runs.map((r,i)=><article key={r.id} style={{borderTopColor:palette[i]}}><span className="eyebrow">SELECTION {i+1}</span><h3>{r.site_name}</h3><Link to={`/runs/${r.id}`}>Plan #{r.id} · {r.status}</Link><small>{timestamp(r.horizon_start)} · {r.weather_source}</small><small>Settings v{r.configuration_version}</small></article>)}</div>
 {data.limitations.map((r,i)=><p className="notice amber" key={i}>{r}</p>)}<div className="section-heading"><div className="segmented"><button aria-pressed={view==='metrics'} onClick={()=>setView('metrics')}>Daily measures</button><button aria-pressed={view==='hourly'} disabled={!data.comparable} onClick={()=>setView('hourly')}>Hourly response</button></div><label className="source-field">{view==='metrics'?'Measure':'Hourly measure'}<select aria-label="Comparison measure" value={view==='metrics'?metric:series} onChange={e=>view==='metrics'?setMetric(e.target.value):setSeries(e.target.value)}>{(view==='metrics'?measures:hourly).map(([key,label,unit])=><option value={key} key={key}>{label} ({unit})</option>)}</select></label></div>
 <div className="readable-chart compact"><ResponsiveContainer>{view==='metrics'?<BarChart data={data.runs.map((r,i)=>({name:`#${r.id}`,value:r.metrics[metric],fill:palette[i]}))}><CartesianGrid vertical={false}/><XAxis dataKey="name"/><YAxis width={70}/><Tooltip formatter={v=>`${n(v,m[3])} ${m[2]}`}/><Bar name={m[1]} dataKey="value" radius={[5,5,0,0]} maxBarSize={85} isAnimationActive={false}/></BarChart>:<LineChart data={points}><CartesianGrid vertical={false}/><XAxis dataKey="time" tickFormatter={v=>new Date(v).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:data.runs[0].snapshot.site.timezone})} minTickGap={55}/><YAxis width={65}/><Tooltip labelFormatter={timestamp} formatter={v=>`${n(v,2)} ${h[2]}`}/>{data.runs.map((r,i)=><Line key={r.id} dataKey={'r'+i} name={`${r.site_name} · #${r.id}`} stroke={palette[i]} type="stepAfter" dot={false} strokeWidth={2} isAnimationActive={false}/>)}</LineChart>}</ResponsiveContainer></div>
 <div className="table-scroll"><table className="comparison-table"><thead><tr><th>Daily measure</th>{data.runs.map(r=><th key={r.id}>#{r.id}</th>)}{data.comparable&&data.runs.length===2&&<th>Second − first</th>}</tr></thead><tbody>{measures.map(([key,label,unit,d])=><tr key={key}><th scope="row">{label}<small>{unit}</small></th>{data.runs.map(r=><td key={r.id}>{n(r.metrics[key],d)}</td>)}{data.comparable&&data.runs.length===2&&<td>{n(data.delta[key],d)}</td>}</tr>)}</tbody></table></div><p className="chart-caption">Per-kWh values use supplied energy. “—” means no valid denominator or schedule. Renewable share uses generated energy; storage is not counted twice. Differences are projections.</p><ExportMenu selection={{kind:'comparison',run_ids:data.runs.map(r=>r.id)}}/></div>;
}
export default function ComparisonWindow({siteIds,runIds,onClose}) {
 const [data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;api('/comparisons',{method:'POST',body:{site_ids:siteIds,run_ids:runIds}}).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[JSON.stringify(siteIds),JSON.stringify(runIds)]);
 return <Dialog title="Compare energy sites & plans" className="comparison-dialog" onClose={onClose}><ErrorNotice error={error}/>{data?<ComparisonDetails data={data}/>:!error&&<p role="status">Loading saved plans…</p>}</Dialog>;
}
