import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Sun,Wind,Battery,Zap,Play,Pause,Activity,Download} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,Legend,CartesianGrid} from 'recharts';
import {api,accessToken,downloadDataset} from './api';
import './live.css';

const n=(value,d=1)=>value==null?'—':Number(value).toLocaleString('en-IN',{maximumFractionDigits:d});
const clock=(value,tz)=>value?new Date(value).toLocaleTimeString('en-GB',{timeZone:tz}):'—';
const strategies=[['lowest_cost','Lowest cost'],['balanced','Balanced'],['lowest_emissions','Lowest emissions']];

export default function LiveControl({site,user}) {
  const [data,setData]=useState(null),[connection,setConnection]=useState('Connecting'),[error,setError]=useState('');
  const [busy,setBusy]=useState(''),[reason,setReason]=useState(''),[comparison,setComparison]=useState(null);
  const [options,setOptions]=useState({speed:10,strategy:'balanced',use_ml:true,conservative:true,carbon_price_inr_per_kg:5});
  useEffect(()=>{
    let active=true,socket,timer;
    async function connect(){
      try{
        const value=await api(`/sites/${site.id}/live`);if(!active)return;setData(value);if(value.session?.active)setOptions(value.session.options);
        socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/sites/${site.id}/live`);
        socket.onopen=()=>{socket.send(JSON.stringify({access:accessToken()}));};
        socket.onmessage=e=>{if(active){setData(JSON.parse(e.data));setConnection('Live stream connected');}};
        socket.onclose=()=>{if(active){setConnection('Disconnected · reconnecting');timer=setTimeout(connect,3000);}};
        socket.onerror=()=>socket.close();
      }catch(e){if(active){setError(e.message);timer=setTimeout(connect,5000);}}
    }
    connect();return()=>{active=false;clearTimeout(timer);socket?.close();};
  },[site.id]);
  async function task(name,fn){setBusy(name);setError('');try{await fn();setData(await api(`/sites/${site.id}/live`));}catch(e){setError(e.message);}finally{setBusy('');}}
  const session=data?.session,t=session?.telemetry,run=session?.run,metrics=run?.metrics||{},evidence=session?.evidence||{};
  const report=data?.model?.report,pending=session?.commands?.find(c=>c.status==='proposed');
  const post=(path,body)=>api(`/sites/${site.id}${path}`,{method:'POST',body});
  const change=(key,value)=>setOptions(v=>({...v,[key]:value}));
  return <div className="live-workspace">
    <section className="panel live-intro"><div><div className="eyebrow">SOFTWARE MICROGRID · SIMULATED TELEMETRY</div><h2>Watch. Replan. Review.</h2><p>Test how your microgrid responds as conditions change. Equipment actions execute inside this simulator.</p></div><span className="badge"><Activity size={14}/>{connection}</span></section>
    {error&&<div className="error" role="alert">{error}</div>}
    {session?.active&&session.stale&&<div className="notice amber" role="alert">Telemetry is stale. Check that the live worker is running. Displayed readings are not current.</div>}
    <section className="panel"><div className="live-options">
      <label>Clock speed<select aria-label="Clock speed" disabled={session?.active} value={options.speed} onChange={e=>change('speed',Number(e.target.value))}><option value={1}>1× · real elapsed time</option><option value={10}>10× · five minutes in 30 seconds</option><option value={30}>30× · five minutes in 10 seconds</option><option value={120}>120× · fast replay</option></select></label>
      <label>Dispatch preference<select aria-label="Dispatch preference" disabled={session?.active} value={options.strategy} onChange={e=>change('strategy',e.target.value)}>{strategies.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
      {options.strategy==='balanced'&&<label>Carbon value (INR/kg CO₂)<input aria-label="Carbon value" type="number" min="0" max="1000" value={options.carbon_price_inr_per_kg} disabled={session?.active} onChange={e=>change('carbon_price_inr_per_kg',Number(e.target.value))}/></label>}
      <label className="check"><input type="checkbox" checked={options.conservative} disabled={session?.active} onChange={e=>change('conservative',e.target.checked)}/>Conservative forecast</label>
      <label className="check"><input type="checkbox" checked={options.use_ml} disabled={session?.active} onChange={e=>change('use_ml',e.target.checked)}/>Use validated ML when available</label>
      <button className="primary" disabled={!!busy||site.archived} onClick={()=>task('session',()=>post('/live',{action:session?.active?'pause':'start',options}))}>{session?.active?<Pause size={16}/>:<Play size={16}/>} {busy==='session'?'Updating…':session?.active?'Pause simulation':'Start simulation'}</button>
    </div><p className="small">Each new session starts at local noon using saved site settings. Pausing preserves its runs and evidence. Five-minute replanning follows the simulated clock; the dispatch model uses hourly intervals.</p></section>
    {session&&<><div className="live-clock"><strong>{clock(session.simulated_at,site.timezone)}</strong><span>{session.options.speed}× simulation · {session.active?'Running':'Paused'} · last plan {clock(session.last_plan_at,site.timezone)}</span></div>
      <div className="live-flow">{[[Sun,'Solar',t?.solar_kw,'kW'],[Wind,'Wind',t?.wind_kw,'kW'],[Battery,'Battery SOC',t?.soc_pct,'%'],[Zap,'Diesel output',t?.generator_kw,'kW']].map(([Icon,label,value,unit])=><div className="panel" key={label}><Icon/><span>{label}</span><strong>{n(value)} <small>{unit}</small></strong></div>)}<div className="panel live-load"><Activity/><span>Community demand</span><strong>{n(t?.demand_kw)} <small>kW</small></strong><small>Supplied {n(t?.served_kw)} kW</small></div></div>
      <p className="small">Battery charging {n(t?.battery_charge_kw)} kW · discharging {n(t?.battery_discharge_kw)} kW · fuel remaining {n(t?.fuel_l)} L · balance residual {n(t?.balance_error_kw,5)} kW</p>
      <section className="panel"><h2>Introduce a change</h2><p>Events change this simulation only. The next worker tick detects the change and recalculates the plan.</p><div className="actions live-events">{[['cloud','Cloud cover −75%'],['high_demand','Demand +50%'],['low_battery','Battery at 25%'],['generator_outage','Generator outage'],['restore','Restore conditions']].map(([event,label])=><button key={event} className="secondary" disabled={!!busy||!session.active} onClick={()=>task(event,()=>post('/live/events',{event}))}>{label}</button>)}</div></section>
      <div className="two-col"><section className="panel"><div className="eyebrow">NEXT OPERATOR DECISION</div><h2>{pending?'Review proposed setpoints':'No proposal awaiting review'}</h2>{pending?<><p>{pending.proposal.reason}</p><div className="summary-row"><span>Generator</span><b>{pending.proposal.generator_on?`Run at ${n(pending.proposal.generator_kw)} kW`:'Switch off / remain off'}</b></div><p>Battery: {pending.proposal.battery_policy}.</p><p>Flexible loads: {pending.proposal.flexible_tasks.map(f=>`${f.name}: ${n(f.power_kw)} kW`).join('; ')||'None configured'}</p><small>Proposal #{pending.id} expires at {clock(pending.expires_at,site.timezone)}.</small><label className="field">Review reason<input aria-label="Command review reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required when rejecting" maxLength={500}/></label><div className="actions"><button className="primary" disabled={!!busy||session.stale||!session.active} onClick={()=>task('approve',()=>post(`/live/commands/${pending.id}`,{decision:'approve',reason}))}>Approve simulated command</button><button className="secondary" disabled={!!busy||!reason.trim()} onClick={()=>task('reject',()=>post(`/live/commands/${pending.id}`,{decision:'reject',reason}))}>Reject</button></div></>:<p>Approved commands execute on the next simulator tick. Their status changes to verified only when simulated output reaches the requested setpoint.</p>}</section>
      <section className="panel"><div className="eyebrow">PROJECTED NEXT 24 HOURS</div><h2>{run?`Plan #${run.id} · ${run.status}`:'Preparing plan'}</h2><div className="summary-row"><span>Critical service</span><b>{n(metrics.critical_load_served_pct)}%</b></div><div className="summary-row"><span>Dispatch cost</span><b>INR {n(metrics.dispatch_cost_inr)}</b></div><div className="summary-row"><span>Diesel / emissions</span><b>{n(metrics.diesel_litres)} L / {n(metrics.emissions_kg_co2)} kg</b></div><div className="summary-row"><span>Lowest battery SOC</span><b>{n(metrics.minimum_soc_pct)}%</b></div><p>{run?.snapshot?.forecast_model?.bounds}</p>{run?.diagnostics?.map((d,i)=><p className="notice amber" key={i}>{d}</p>)}{run&&<Link to={`/runs/${run.id}`}>Inspect saved plan and inputs →</Link>}</section></div>
      {!!session.samples?.length&&<section className="panel"><h2>Forecast and simulated observations</h2><p>Base load/physics forecast against changing simulated conditions; power in kW.</p><div className="live-chart"><ResponsiveContainer><LineChart data={session.samples}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="timestamp" tickFormatter={v=>clock(v,site.timezone)}/><YAxis/><Tooltip labelFormatter={v=>clock(v,site.timezone)}/><Legend/><Line dataKey="demand_kw" name="Observed demand" stroke="#c07724" dot={false}/><Line dataKey="forecast_demand_kw" name="Base demand forecast" stroke="#c07724" strokeDasharray="4 4" dot={false}/><Line dataKey="solar_kw" name="Observed solar" stroke="#13765b" dot={false}/><Line dataKey="forecast_solar_kw" name="Physics solar forecast" stroke="#13765b" strokeDasharray="4 4" dot={false}/></LineChart></ResponsiveContainer></div></section>}
      <section className="panel"><div className="eyebrow">OBSERVED IN THIS SOFTWARE SIMULATION</div><h2>Evidence, with its source attached.</h2><div className="live-evidence">{[['Critical service',`${n(evidence.critical_service_pct)}%`],['Unserved critical energy',`${n(evidence.critical_unserved_kwh,3)} kWh`],['Diesel used',`${n(evidence.diesel_litres)} L`],['Dispatch cost',`INR ${n(evidence.cost_inr)}`],['CO₂ emitted',`${n(evidence.emissions_kg)} kg`],['Verified commands',evidence.verified_commands]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><button className="secondary" onClick={()=>{const blob=new Blob([JSON.stringify({site:site.name,basis:evidence.basis,session_id:session.id,evidence,events:session.events},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`jeevangrid-evidence-${session.id}.json`;a.click();URL.revokeObjectURL(url);}}><Download size={15}/>Export evidence</button></section>
      <details className="panel"><summary>Command audit and event timeline</summary>{session.commands.map(c=><div className="summary-row" key={c.id}><span>#{c.id} · Generator {n(c.proposal.generator_kw)} kW<small>{c.reason||c.result?.error}</small></span><b>{c.status}</b></div>)}<ol className="live-timeline">{[...session.events].reverse().map((e,i)=><li key={i}><time>{clock(e.time,site.timezone)}</time>{e.message}</li>)}</ol></details>
    </>}
    <section className="panel"><h2>Demand forecasting and solar correction</h2><p>XGBoost predicts demand and learns solar errors around the physics estimate. Each model must beat its baseline on a separate calibration period before it is selected.</p>{user.role==='admin'&&<div className="actions"><button className="secondary" disabled={!!busy} onClick={()=>task('train',()=>post('/forecast-model',{source:'simulated'}))}>{busy==='train'?'Training and evaluating…':'Train on 90 simulated days'}</button><label className="secondary">Upload training CSV<input aria-label="Upload training CSV" type="file" accept=".csv" disabled={!!busy} onChange={e=>{if(e.target.files[0])task('train',()=>{const body=new FormData();body.append('file',e.target.files[0]);return post('/forecast-model',body);});}}/></label></div>}
      {report?<><p className="notice">{report.note} · {report.rows} hourly rows · source: {report.provenance}</p><div className="table-scroll"><table><thead><tr><th>Forecast</th><th>Baseline test error</th><th>ML test error</th><th>Selected model</th></tr></thead><tbody>{['demand','solar'].map(key=><tr key={key}><td>{key==='demand'?'Demand':'Solar residual correction'}</td><td>{n(report[key].baseline_mae_kw,3)} kW MAE</td><td>{n(report[key].ml_mae_kw,3)} kW MAE</td><td>{report[key].active?'XGBoost':'Baseline (ML did not qualify)'}</td></tr>)}</tbody></table></div><p className="small">MAE is average absolute error; lower is better. Synthetic training models are used only in simulated runs.</p><button className="secondary" onClick={()=>task('download',()=>downloadDataset(site.id))}>Download training dataset CSV</button><details><summary>Evaluation dates and held-out forecast graph</summary>{Object.entries(report.split).map(([label,dates])=><p key={label}>{label}: {dates.join(' → ')}</p>)}<div className="live-chart"><ResponsiveContainer><LineChart data={report.demand.evaluation}><XAxis dataKey="timestamp" tickFormatter={v=>clock(v,site.timezone)}/><YAxis/><Tooltip/><Legend/><Line dataKey="actual" stroke="#13765b" dot={false}/><Line dataKey="baseline" stroke="#a6acb0" dot={false}/><Line dataKey="forecast" stroke="#c07724" dot={false}/></LineChart></ResponsiveContainer></div></details></>:<p>No trained model yet. The optimizer uses the existing load template and physics estimates.</p>}
    </section>
    <section className="panel"><h2>Cost and emissions trade-off</h2><p>Compare the three strategies against exactly the same inputs. Critical service remains the first priority. Some sites have the same best plan for all three strategies.</p><button className="secondary" disabled={!!busy} onClick={()=>task('compare',async()=>setComparison(await post('/live/strategies',{})))}>{busy==='compare'?'Comparing…':'Compare strategies'}</button>{comparison&&<div className="table-scroll"><table><thead><tr><th>Strategy</th><th>Result</th><th>Critical service</th><th>Cost (INR)</th><th>Diesel (L)</th><th>CO₂ (kg)</th></tr></thead><tbody>{comparison.results.map(r=><tr key={r.strategy}><td>{r.strategy.replaceAll('_',' ')}</td><td>{r.status}</td><td>{n(r.metrics.critical_load_served_pct)}%</td><td>{n(r.metrics.dispatch_cost_inr)}</td><td>{n(r.metrics.diesel_litres)}</td><td>{n(r.metrics.emissions_kg_co2)}</td></tr>)}</tbody></table><p>{comparison.basis}</p></div>}</section>
    <details className="panel"><summary>Guided demonstration · five steps</summary><ol><li>Train on 90 simulated days and inspect both test errors.</li><li>Start the simulation at 10×. Wait for the live stream and first proposal.</li><li>Approve a proposal and watch the command audit reach verified.</li><li>Apply Cloud cover, then Battery at 25%. Inspect the new plan before approving it.</li><li>Apply Generator outage. Explain the measured shortage or continued service using the evidence cards; export the record.</li></ol><p>Zero diesel savings or a critical shortage are valid results. Describe what the configured equipment actually achieved.</p></details>
  </div>;
}
