import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,NavLink,Link,Navigate,useNavigate,useParams,useLocation} from 'react-router-dom';
import {Sun,Wind,Battery,LayoutDashboard,MapPin,User,Users,Database,ArrowUpRight,ArrowLeft,Plus,LogOut,Check,AlertTriangle,RefreshCw,Zap,ChevronRight} from 'lucide-react';
import {api,tokens,hasSession,refreshToken} from './api';
import './style.css';
import './intelligence.css';
import './workspace.css';
import './assistant.css';
import AssistantPage,{AssistantWidget} from './Assistant';
import {MessageSquare} from 'lucide-react';
import Login from './Login';
import Landing from './Landing';
import Brand from './Brand';
import {EquipmentOverview,DemandMix} from './EnergyVisuals';
import {Search,ShieldCheck} from 'lucide-react';
import Portfolio from './Portfolio';
import SitePage from './SiteWorkspace';
import DataWorkspace,{TeamWorkspace} from './DataWorkspace';
import RunPage from './SavedRun';
import {Metric as Stat} from './ui';

const fmt=(v,d=1)=>v===null||v===undefined?'—':Number(v).toLocaleString('en-IN',{maximumFractionDigits:d});
const INDIA_STATES=['Andaman and Nicobar Islands','Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chandigarh','Chhattisgarh','Dadra and Nagar Haveli and Daman and Diu','Delhi','Goa','Gujarat','Haryana','Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala','Ladakh','Lakshadweep','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Puducherry','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal'];
function Badge({value}){return <span className={`badge ${value||'neutral'}`}><i/>{String(value||'not assessed').replaceAll('_',' ')}</span>}
function ErrorBox({error}){return error?<div role="alert" className="error"><AlertTriangle size={17}/>{error}</div>:null}
function Loading(){return <div className="loading"><RefreshCw className="spin" size={20}/>Loading workspace…</div>}
function Header({eyebrow,title,description,children}){return <header className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="actions">{children}</div></header>}
function RequiredLabel({children,required}){return <span>{children}{required&&<em className="required-mark" aria-hidden="true">*</em>}</span>}
function Field({label,value,onChange,type='number',help,required=false,...props}){return <label className="field"><RequiredLabel required={required}>{label}</RequiredLabel><input aria-label={props['aria-label']||label} type={type} value={value??''} required={required} onChange={e=>onChange(type==='number'?e.target.value===''?'':Number(e.target.value):e.target.value)} {...props}/>{help&&<small>{help}</small>}</label>}
function WorkspaceHeader({user}) {
 const {pathname}=useLocation();
 const section=pathname==='/assistant'?'Assistant':pathname==='/team'?'People & access':pathname==='/account'?'Account':pathname==='/data'?'Data explorer':pathname.includes('/edit')||pathname==='/sites/new'?'Site configuration':pathname.startsWith('/sites/')?'Site operations':pathname==='/sites'?'Sites':pathname.startsWith('/runs/')?'Saved plan':user.role==='admin'?'Portfolio':'My sites';
 return <div className="topbar"><div className="breadcrumb"><Link to="/workspace">Workspace</Link><ChevronRight size={13}/><span>{section}</span></div><div className="topbar-account"><span className="workspace-label">Energy planning</span><Link to="/account" className="user-chip"><span className="user-avatar">{user.name.slice(0,1)}</span><b>{user.name}</b></Link></div></div>;
}
function App(){
  const location=useLocation(),navigate=useNavigate();
  useEffect(()=>{window.scrollTo({top:0,left:0,behavior:'instant'})},[location.pathname]);
  const [user,setUser]=useState(null),[loading,setLoading]=useState(hasSession());
  useEffect(()=>{if(hasSession())api('/auth/me').then(setUser).catch(()=>tokens(null)).finally(()=>setLoading(false));const expired=()=>setUser(null);window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired)},[]);
  if(location.pathname==='/')return <Landing/>;
  if(loading)return <Loading/>;
  if(!user)return <Login onLogin={value=>{setUser(value);if(location.pathname==='/login')navigate('/workspace',{replace:true})}}/>;
  if(location.pathname==='/login')return <Navigate to="/workspace" replace/>;
  const isAdmin=user.role==='admin';
  const nav=isAdmin?[['/workspace','Portfolio',LayoutDashboard],['/sites','Sites',MapPin],['/data','Data explorer',Database],['/team','People & access',Users],['/assistant','Assistant',MessageSquare],['/account','Account',User]]:[['/workspace','My sites',MapPin],['/data','Data explorer',Database],['/assistant','Assistant',MessageSquare],['/account','Account',User]];
  async function signout(){try{await api('/auth/logout',{method:'POST',body:{refresh:refreshToken()}})}finally{tokens(null);setUser(null);navigate('/',{replace:true})}}
  return <><a className="skip-link" href="#workspace-content">Skip to workspace</a><div className="shell"><aside className="sidebar"><Link to="/workspace" className="brand"><Brand/></Link><div className="org">{user.organization}<span>{isAdmin?'Organization admin':'Site operator'}</span></div><div className="nav-label">WORKSPACE</div><nav aria-label="Workspace navigation">{nav.map(([to,text,Icon])=><NavLink end={to==='/workspace'} key={to} to={to}><Icon size={18}/>{text}</NavLink>)}</nav><div className="sidebar-bottom"><div className="advisory"><span className="live-dot"/>Advisory workspace<small>Projected plans & simulations.</small></div><button className="logout" onClick={signout}><LogOut size={17}/>Sign out</button></div></aside><div className="main"><WorkspaceHeader user={user}/><main id="workspace-content" className="content" tabIndex={-1}><Routes><Route path="/assistant" element={<AssistantPage user={user}/>}/><Route path="/workspace" element={isAdmin?<Portfolio/>:<Sites user={user}/>}/><Route path="/sites" element={<Sites user={user}/>}/><Route path="/sites/new" element={isAdmin?<Wizard/>:<Sites user={user}/>}/><Route path="/sites/:id/edit" element={isAdmin?<Wizard/>:<Sites user={user}/>}/><Route path="/sites/:id" element={<SitePage user={user}/>}/><Route path="/data" element={<DataWorkspace user={user}/>}/><Route path="/team" element={isAdmin?<TeamWorkspace/>:<Account user={user}/>}/><Route path="/history" element={<DataWorkspace user={user}/>}/><Route path="/simulations" element={<DataWorkspace user={user}/>}/><Route path="/runs/:id" element={<RunPage/>}/><Route path="/account" element={<Account user={user}/>}/><Route path="*" element={<div className="empty">Page not found. <Link to="/workspace">Return home</Link></div>}/></Routes><footer>JeevanGrid · All energy plans are advisory. Metrics are projected unless explicitly labelled measured.</footer></main></div></div><AssistantWidget user={user}/></>
}

function Sites({user}){
 const [sites,setSites]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('active');
 useEffect(()=>{const load=()=>api('/sites').then(setSites).catch(e=>setError(e.message));load();window.addEventListener('jg-data-changed',load);return()=>window.removeEventListener('jg-data-changed',load)},[]);
 const shown=(sites||[]).filter(s=>(filter==='all'||!s.archived)&&`${s.name} ${s.district} ${s.state}`.toLowerCase().includes(query.toLowerCase()));
 return <><Header eyebrow="SITE WORKSPACE" title={user.role==='admin'?'Microgrid sites':'Assigned sites'} description="Your communities. Their energy. One place to manage it.">{user.role==='admin'&&<Link className="primary" to="/sites/new"><Plus size={17}/>Add site</Link>}</Header><ErrorBox error={error}/><div className="site-toolbar"><label className="search-field"><Search size={18}/><input aria-label="Search sites" placeholder="Search by site, district or state" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="segmented"><button aria-pressed={filter==='active'} onClick={()=>setFilter('active')}>Active sites</button><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>Include archived</button></div><span>{shown.length} sites</span></div>{!sites?<Loading/>:<div className="site-grid">{shown.map(s=>{const m=s.latest_run?.metrics;return <Link className={`site-card ${s.archived?'archived':''}`} key={s.id} to={`/sites/${s.id}`}><div className="site-card-top"><MapPin/><Badge value={s.archived?'archived':s.latest_run?.status}/></div><div className="eyebrow">{s.state}</div><h2>{s.name}</h2><p>{s.district}</p>{m?<div className="site-energy-preview"><div><span>Renewable generation</span><b>{fmt(m.renewable_share_pct)}%</b></div><div className="balance-bar" role="img" aria-label={`${fmt(m.renewable_share_pct)} percent renewable generation`}><span style={{width:`${Math.max(0,Math.min(100,m.renewable_share_pct||0))}%`}}/></div><div className="site-plan-facts"><span><b>{fmt(m.critical_load_served_pct)}%</b> critical served</span><span><b>{fmt(m.diesel_litres)} L</b> diesel</span></div></div>:<div className="site-no-plan">Ready for its first operating plan</div>}<div className="site-card-footer"><span>{s.operators.length} assigned operator{s.operators.length===1?'':'s'}</span><b>Open site <ArrowUpRight size={15}/></b></div></Link>})}{!shown.length&&<div className="empty">No sites match this search.</div>}</div>}</>
}

function Account({user}){return <><Header eyebrow="ACCOUNT" title="Account details"/><section className="panel form-panel account-panel"><div className="account-cover"><ShieldCheck size={30}/><span>WORKSPACE IDENTITY</span></div><div className="account-avatar">{user.name.slice(0,1)}</div><h2>{user.name}</h2><p>{user.email}</p><div className="summary-row"><span>Organization</span><b>{user.organization}</b></div><div className="summary-row"><span>Role</span><Badge value={user.role}/></div><p>{user.role==='admin'?'You can configure sites, assign operators and compare the organization portfolio.':'You can update operating readings, run plans and review recommendations for assigned sites.'}</p><button className="secondary" onClick={async()=>{await api('/auth/logout',{method:'POST',body:{refresh:refreshToken()}}).catch(()=>{});tokens(null);window.location.assign('/')}}><LogOut size={16}/>Sign out of this account</button></section></>}

const configLabels={capacity_kw:'Rated capacity (kW)',tilt:'Panel tilt (degrees)',azimuth:'Panel azimuth (degrees)',derating:'PV derating factor',inverter_efficiency:'Inverter efficiency',hub_height_m:'Hub height (m)',cut_in:'Cut-in wind speed (m/s)',rated_speed:'Rated wind speed (m/s)',cut_out:'Cut-out wind speed (m/s)',shear_exponent:'Wind height exponent',capacity_kwh:'Battery capacity (kWh)',min_soc:'Minimum safe SOC (%)',max_soc:'Maximum SOC (%)',reserve_soc:'Operating reserve SOC (%)',max_charge_kw:'Max charge power (kW)',max_discharge_kw:'Max discharge power (kW)',charge_efficiency:'Charge efficiency',discharge_efficiency:'Discharge efficiency',replacement_cost:'Replacement cost (INR)',lifetime_throughput_kwh:'Lifetime discharge throughput (kWh)',min_power_kw:'Minimum stable output (kW)',fuel_slope:'Fuel slope (L/kWh)',fuel_intercept:'No-load fuel (L/hour)',start_cost:'Cost per start (INR)',diesel_price:'Diesel price (INR/L)',available_fuel_l:'Default fuel available (L)',emissions_factor:'CO₂ factor (kg/L)',critical_target_pct:'Critical service target (%)',renewable_target_pct:'Renewable generation target (%)',terminal_soc:'End-of-plan reserve SOC (%)',max_starts:'Maximum generator starts',curtailment_penalty:'Curtailment penalty (INR/kWh)',renewable_shortfall_penalty:'Renewable shortfall penalty (INR/kWh)'};
function Wizard(){
 Object.assign(configLabels,{min_up_hours:'Minimum generator run (hours)',min_down_hours:'Minimum cooldown (hours)',ramp_kw_per_hour:'Generator ramp limit (kW/hour)'});
 const {id}=useParams();const navigate=useNavigate();const [step,setStep]=useState(0),[c,setC]=useState(null),[site,setSite]=useState({name:'',state:'Arunachal Pradesh',district:'Papum Pare',latitude:27.2297,longitude:93.3412,timezone:'Asia/Kolkata',operator_ids:[]}),[members,setMembers]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[places,setPlaces]=useState([]),[locationQuery,setLocationQuery]=useState(''),[locationStatus,setLocationStatus]=useState(''),[locationTouched,setLocationTouched]=useState(false);
 useEffect(()=>{Promise.all([id?api(`/sites/${id}`):api('/defaults'),api('/members')]).then(([d,m])=>{setMembers(m);if(id){setC(d.configuration);setSite(Object.fromEntries(['name','state','district','latitude','longitude','timezone','operator_ids'].map(k=>[k,d[k]])));setLocationQuery(d.district)}else setC(d)}).catch(e=>setError(e.message))},[id]);
 useEffect(()=>{if(!locationTouched||locationQuery.trim().length<3)return;let active=true;setLocationStatus('Searching locations…');const timer=setTimeout(()=>api(`/locations/search?q=${encodeURIComponent(locationQuery.trim())}`).then(d=>{if(active){setPlaces(d.results);if(d.results.length){const best=d.results[0];setSite(current=>siteFromPlace(current,best));setLocationStatus(`Coordinates automatically filled using ${best.label}. Choose another match below if needed.`)}else setLocationStatus('No matching place found. Refine the name or enter coordinates manually.')}}).catch(e=>{if(active){setPlaces([]);setLocationStatus(e.message)}}),450);return()=>{active=false;clearTimeout(timer)}},[locationQuery,locationTouched]);
 const change=(section,key,val)=>setC({...c,[section]:{...c[section],[key]:val,provenance:'operator'}});
 function changeDemand(key,value){const next=structuredClone(c);next.demand[key]=value;next.demand.provenance='simulated';const target=next.demand.daily_kwh*next.demand.flexible_pct/100;const old=next.flexible_loads.reduce((s,f)=>s+f.required_kwh,0);if(old)next.flexible_loads.forEach(f=>{f.required_kwh=f.required_kwh*target/old});setC(next)}
 function siteFromPlace(current,place){return {...current,state:place.state||current.state,district:place.district,latitude:place.latitude,longitude:place.longitude,timezone:place.timezone}}
 function choosePlace(place){setSite(current=>siteFromPlace(current,place));setLocationQuery(place.name);setPlaces([]);setLocationTouched(false);setLocationStatus(`Coordinates filled from ${place.label}.${place.state_verified?'':' The source did not include a state hierarchy, so verify the state and coordinates.'}`)}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const r=await api(id?`/sites/${id}`:'/sites',{method:id?'PATCH':'POST',body:{...site,configuration:c}});navigate(`/sites/${r.id}`)}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(!c)return <><ErrorBox error={error}/><Loading/></>;
 const section=(key,keys)=> <div className="form-grid">{keys.map(k=><Field key={k} label={configLabels[k]||k} value={c[key][k]} onChange={v=>change(key,k,v)} step="any" required/>)}</div>;
 return <><Link className="back" to={id?`/sites/${id}`:'/sites'}><ArrowLeft size={15}/>Back</Link><Header eyebrow="SITE CONFIGURATION" title={id?'Site configuration':'Add a microgrid site'} description="Set the location, equipment, demand and operating limits used for planning."/><div className="steps">{['Location','Equipment','Demand & loads','Costs & rules','Review'].map((s,i)=><button className={i===step?'active':''} key={s} onClick={()=>setStep(i)}><span>{i+1}</span>{s}</button>)}</div><ErrorBox error={error}/><form onSubmit={save}><section className="panel"><p className="required-note"><span>*</span> Required fields</p>
 {step===0&&<><h2>Where does this microgrid operate?</h2><p>Search anywhere in India using a village, town or district name. The best match fills the state, district, coordinates and timezone immediately.</p><div className="form-grid"><Field label="Site name" type="text" value={site.name} onChange={v=>setSite({...site,name:v})} required/><div className="location-field"><Field label="Search location" type="search" value={locationQuery} onChange={v=>{setLocationQuery(v);setSite({...site,latitude:'',longitude:''});setLocationTouched(true)}} required autoComplete="off" placeholder="Try ahm for Ahmedabad" help="Type at least 3 characters. Coordinates fill from the first result automatically."/>{locationStatus&&<small className="location-status">{locationStatus}</small>}{places.length>0&&<div className="location-results" role="listbox" aria-label="Location matches">{places.map(p=><button type="button" role="option" key={p.id||`${p.latitude}-${p.longitude}`} onClick={()=>choosePlace(p)}><MapPin size={15}/><span>{p.label}<small>{p.latitude.toFixed(4)}, {p.longitude.toFixed(4)}</small></span></button>)}</div>}</div><Field label="State or union territory" type="text" list="india-state-options" value={site.state} onChange={v=>setSite({...site,state:v})} required autoComplete="off" help="Searchable list; start typing, for example Guj or Arun."/><datalist id="india-state-options">{INDIA_STATES.map(s=><option key={s} value={s}/>)}</datalist><Field label="District" type="text" value={site.district} onChange={v=>setSite({...site,district:v})} required help="Filled from the selected location; editable if the source uses a different district name."/><Field label="Latitude" value={site.latitude} onChange={v=>setSite({...site,latitude:v})} min="-90" max="90" step="any" required help="Automatically filled from the best location match."/><Field label="Longitude" value={site.longitude} onChange={v=>setSite({...site,longitude:v})} min="-180" max="180" step="any" required help="WGS84 coordinate used by the weather services."/><Field label="Timezone" type="text" value={site.timezone} onChange={v=>setSite({...site,timezone:v})} required help="Automatically resolved with the location."/></div><p className="small">Location search: Open-Meteo geocoding, based on GeoNames. Always verify the match for remote communities or repeated place names.</p><h3>Assigned operators <span className="optional">Optional</span></h3>{members.map(m=><label className="check" key={m.user_id}><input type="checkbox" checked={site.operator_ids.includes(m.user_id)} onChange={e=>setSite({...site,operator_ids:e.target.checked?[...site.operator_ids,m.user_id]:site.operator_ids.filter(i=>i!==m.user_id)})}/>{m.user__email}</label>)}</>}
 {step===1&&<><h2>Equipment and engineering limits</h2><p>Zero solar or wind capacity disables that source. Efficiencies are fractions between 0 and 1.</p><EquipmentOverview configuration={c}/><h3><Sun size={18}/>Solar PV</h3>{section('solar',['capacity_kw','tilt','azimuth','derating','inverter_efficiency'])}<h3><Wind size={18}/>Wind</h3>{section('wind',['capacity_kw','hub_height_m','cut_in','rated_speed','cut_out','shear_exponent'])}<h3><Battery size={18}/>Battery storage</h3>{section('battery',['capacity_kwh','min_soc','max_soc','reserve_soc','max_charge_kw','max_discharge_kw','charge_efficiency','discharge_efficiency'])}<h3><Zap size={18}/>Diesel backup</h3>{section('generator',['capacity_kw','min_power_kw','min_up_hours','min_down_hours','ramp_kw_per_hour'])}<p className="small">Minimum run and cooldown are whole hours. The ramp applies between running setpoints; startup may step to minimum stable power. New operational defaults are engineering assumptions, not study measurements.</p></>}
 {step===2&&<><h2>Community demand and flexible work</h2><p>Demand is split into critical, normal and flexible energy. Flexible tasks replace the flexible portion; they are not added twice.</p><div className="form-grid">{[['daily_kwh','Daily energy (kWh)'],['peak_kw','Reference hourly peak (kW)'],['critical_pct','Critical share (%)'],['flexible_pct','Flexible share (%)']].map(([k,l])=><Field label={l} key={k} value={c.demand[k]} onChange={v=>changeDemand(k,v)} step="any" required/>)}</div><DemandMix demand={c.demand}/><p>Normal share: {fmt(100-c.demand.critical_pct-c.demand.flexible_pct)}% · Required flexible work: {fmt(c.demand.daily_kwh*c.demand.flexible_pct/100,3)} kWh</p><div className="section-heading"><h3>Dispatchable loads</h3><button type="button" className="secondary" onClick={()=>setC({...c,flexible_loads:[...c.flexible_loads,{name:'New flexible task',power_kw:10,required_kwh:0,start_hour:9,end_hour:17,priority:'flexible',provenance:'operator'}]})}><Plus size={16}/>Add load</button></div>{c.flexible_loads.map((f,i)=><div className="flex-load" key={i}><div className="form-grid">{[['name','Load name','text'],['power_kw','Max operating power (kW)','number'],['required_kwh','Required energy (kWh/day)','number'],['start_hour','Earliest local hour','number'],['end_hour','Latest local hour (exclusive)','number']].map(([k,l,t])=><Field key={k} label={l} type={t} value={f[k]} step="any" required onChange={v=>setC({...c,flexible_loads:c.flexible_loads.map((x,j)=>j===i?{...x,[k]:v,provenance:'operator'}:x)})}/>)}</div><button type="button" className="text-button" onClick={()=>setC({...c,flexible_loads:c.flexible_loads.filter((_,j)=>j!==i)})}>Remove load</button></div>)}<p className="small">V1 models divisible scheduled energy, suitable for pumping within a daily window. It does not model refrigerator temperature or appliance switching. Changing demand replaces an imported daily template.</p></>}
 {step===3&&<><h2>Cost inputs and operating rules</h2><h3>Generator costs</h3>{section('generator',['fuel_slope','fuel_intercept','start_cost','diesel_price','available_fuel_l','emissions_factor'])}<h3>Battery wear</h3>{section('battery',['replacement_cost','lifetime_throughput_kwh'])}<p>Estimated wear: INR {fmt(c.battery.replacement_cost/c.battery.lifetime_throughput_kwh,3)} per discharged kWh.</p><h3>Reliability and renewable targets</h3>{section('policy',['critical_target_pct','renewable_target_pct','terminal_soc','max_starts'])}<details><summary>Advanced planning penalties</summary>{section('policy',['curtailment_penalty','renewable_shortfall_penalty'])}</details><h3>Allowed generator hours (local time)</h3><div className="hours">{Array.from({length:24},(_,h)=><label key={h}><input type="checkbox" checked={c.policy.allowed_generator_hours.includes(h)} onChange={e=>change('policy','allowed_generator_hours',e.target.checked?[...c.policy.allowed_generator_hours,h].sort((a,b)=>a-b):c.policy.allowed_generator_hours.filter(x=>x!==h))}/>{String(h).padStart(2,'0')}</label>)}</div></>}
 {step===4&&<><h2>Review before saving</h2><div className="stats"><Stat label="Daily demand" value={fmt(c.demand.daily_kwh)} unit="kWh"/><Stat label="Solar / wind" value={`${fmt(c.solar.capacity_kw)} / ${fmt(c.wind.capacity_kw)}`} unit="kW"/><Stat label="Battery" value={fmt(c.battery.capacity_kwh)} unit="kWh"/><Stat label="Backup generator" value={fmt(c.generator.capacity_kw)} unit="kW"/></div><p><b>{site.name||'Unnamed site'}</b> · {site.district}, {site.state}</p><p>Critical demand {c.demand.critical_pct}% · Renewable target {c.policy.renewable_target_pct}% · End reserve {c.policy.terminal_soc}%</p><div className="notice">The starting template uses study-reported capacities and assumed operating values. Verify each input against this site's equipment. Critical priorities and flexible schedules require local agreement.</div><details><summary>All settings and provenance</summary><pre>{JSON.stringify(c,null,2)}</pre></details></>}
 <div className="wizard-actions"><button type="button" className="secondary" disabled={step===0} onClick={()=>setStep(step-1)}>Previous</button>{step<4?<button key="continue" type="button" className="primary" onClick={e=>{e.preventDefault();if(e.currentTarget.closest('form').reportValidity()){setError('');setStep(step+1)}}}>Continue<ChevronRight size={17}/></button>:<button key="save" type="submit" className="primary" disabled={busy}>{busy?'Saving…':'Save site configuration'}<Check size={17}/></button>}</div></section></form></>
}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
